jobs:
  build-all:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      id: go
      name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
    - continue-on-error: true
      name: Force NDK version
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.1.7171670"
    - continue-on-error: true
      name: Build rclone
      run: ./gradlew rclone:buildNative
    - continue-on-error: true
      name: Build app
      run: ./gradlew assembleOssDebug
    - continue-on-error: true
      name: Upload APK (arm)
      uses: actions/upload-artifact@v2
      with:
        name: arm.apk
        path: app/build/outputs/apk/oss/debug/app-oss-armeabi-v7a-debug.apk
        retention-days: 3
    - continue-on-error: true
      name: Upload APK (arm64)
      uses: actions/upload-artifact@v2
      with:
        name: arm64.apk
        path: app/build/outputs/apk/oss/debug/app-oss-arm64-v8a-debug.apk
        retention-days: 3
    - continue-on-error: true
      name: Upload APK (x86)
      uses: actions/upload-artifact@v2
      with:
        name: x86.apk
        path: app/build/outputs/apk/oss/debug/app-oss-x86-debug.apk
        retention-days: 3
    - continue-on-error: true
      name: Upload APK (arm)
      uses: actions/upload-artifact@v2
      with:
        name: x64.apk
        path: app/build/outputs/apk/oss/debug/app-oss-x86_64-debug.apk
        retention-days: 3
    - continue-on-error: true
      name: Upload APK (universal)
      uses: actions/upload-artifact@v2
      with:
        name: universal.apk
        path: app/build/outputs/apk/oss/debug/app-oss-universal-debug.apk
        retention-days: 14
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
